version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d game_library_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
volumes:
  db_data: